### ISSUE TITLE
Not working for WeeWx 4.0

### ISSUE THREAD

**Issue by RayZorb** [matthewwall/weewx-as3935#1]
May 31 19:15:32 WeatherPI systemd[1]: Started LSB: weewx weather system.
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__: Caught unrecoverable exception:
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****  invalid syntax (as3935.py, line 233)
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****  Traceback (most recent call last):
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****    File "/home/weewx/bin/weewxd", line 148, in main
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 75, in __init__
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****      self.loadServices(config_dict)
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 138, in loadServices
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self,config_dict)
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****    File "/home/weewx/bin/weeutil/weeutil.py", line 1093, in get_object
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****      mod = __import__(module)
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****    File "/home/weewx/bin/user/as3935.py", line 233
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****      except Exception, e:
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****                      ^
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****  SyntaxError: invalid syntax
May 31 19:15:32 WeatherPI weewx[9774] CRITICAL __main__:     ****  Exiting.

**Comment by ebonzl** [comment]
Seems to be a Python 3 compatibility issue, would be great if this was working again

**Comment by G5MDC** [comment]
I know that this thread has been open for some time but this is what I have found out. Apparently in python3  'raise syntax no longer accepts comma-separated arguments' I think it may have been left in older versions of Python for backward compatibility.
I am using Python 3.10 and changed line 233 to **except Exception as e:** which resolved the issue (I think!) I am not familiar with GIt HUB and forks etc.  So I thought I would mention it here. Hopefully the author will update the Master.

**Comment by roe-dl** [comment]
See PR #2

**Comment by matthewwall** [comment]
thank you roe-dl and m5djc.  fix is now on master and tagged as v0.7.  beware that this also changes the name of the fields so that they match the lightning observations in the wview_extended schema.  anyone already using the extension will have to change the code or change the column names in the database.  apologies for not having a backward-compatible implementation.
